#!/usr/bin/python3

import sys
import re

# Check if there is pipe input
if not sys.stdin.isatty():
    hasPipe = True
else:
    hasPipe = False

if hasPipe:
    text = sys.stdin.read()
else: # Has arguments instead
    text = open(sys.argv[1])

html = """
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container text-justify">"""

# Make each line a <p>
for line in text.split("\n"):
    hasRemove = line.find("[-") >= 0
    hasAdd    = line.find("{+") >= 0

    # Line that has only the removed portion
    if hasRemove:
        remLine = line
        while remLine.find("{+") >= 0:
            beg = remLine.find("{+")
            end = remLine.find("+}")
            remLine = remLine[:beg] + remLine[end+2:]
        remLine = remLine.replace("[-", """<span style="background-color: tomato; text-decoration: line-through;">""")
        remLine = remLine.replace("-]", """</span>""")

    # Line that has only the added portion
    if hasAdd:
        addLine = line
        while addLine.find("[-") >= 0:
            beg = addLine.find("[-")
            end = addLine.find("-]")
            addLine = addLine[:beg] + addLine[end+2:]
        addLine = addLine.replace("{+", """<span style="background-color: chartreuse;">""")
        addLine = addLine.replace("+}", """</span>""")


    # Add line or lines to the html object
    if hasRemove and hasAdd:
        html += "<p>" + remLine + "<br>" + addLine + "</p>"
    elif hasRemove:
        html += "<p>" + remLine + "</p>"
    elif hasAdd:
        html += "<p>" + addLine + "</p>"
    else:
        html += "<p>" + line + "</p>"

html += """
        </div>
    </body>
</html>"""

print(html)
